# Generated by Django 5.2.7 on 2025-11-15 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.TextField(help_text='Names of participants')),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('agreement_text', models.TextField(blank=True)),
                ('edited_text', models.TextField(blank=True, help_text='User edited version')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reflection', 'In Reflection'), ('review', 'Under Review'), ('signed', 'Signed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=True)),
                ('agreement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agreementtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signing_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='core.agreement')),
            ],
        ),
    ]
